### PR TITLE
Austin dev

### PR DESCRIPTION
**Pull request by ShenghaoisYummy**
fixed comment and change the return type of format_id in utils

### CODE REVIEW

**Comment by ShenghaoisYummy** [comment]
change fomart_id back to string

**Comment by ShenghaoisYummy** [comment]
change fomart_id back to string

**Comment by hoangtd-dev** [comment]
We have 2 `__student_course_menu` func in `cli_enrolment_system`. Remove one of two. Please take the message from requirement.

**Comment by hoangtd-dev** [comment]
We have `__handle_student_course_menu_option` and `__handle_subject_menu_option` is same. Remove one.
If u use `__handle_subject_menu_option`. Add `self.logout()` for `case 'x'`

**Comment by ShenghaoisYummy** [comment]
remove duplicate functions in cli_enrolment_system.py

**Comment by ShenghaoisYummy** [comment]
[fix remove_subject / fix gitignore / fix grade class](https://github.com/hoangtd-dev/EnrolmentSystem/pull/11/commits/7294e17d5e1df16bfc04aeb27b6ed68e69bbff8a)

**Pull request merged**
